# train_data_path: $TMPDIR/src/omnicrack30k_rearranged/train
# validation_data_path: $TMPDIR/src/omnicrack30k_rearranged/validation
train_data_path: $TMPDIR/src/tiny_data/train
validation_data_path: $TMPDIR/src/tiny_data/test

lambda_values: [0.8, 0.9, 1.0]
learning_rates: [0.0001, 0.0005, 0.0009]
batch_sizes: [2, 4, 8]
num_epochs: 2
weight_decay: 0.00005
NUM_EXP: 500
sam2_checkpoint_path: "sam2.1_hiera_tiny.pt"
model_cfg: "configs/sam2.1/sam2.1_hiera_t.yaml"
#sam2_checkpoint_path: "sam2.1_hiera_small.pt"
#model_cfg: "configs/sam2.1/sam2.1_hiera_s.yaml"
#sam2_checkpoint_path: "sam2.1_hiera_base_plus.pt"
#model_cfg: "configs/sam2.1/sam2.1_hiera_b+.yaml"
#sam2_checkpoint_path: "sam2.1_hiera_large.pt"
#model_cfg: "configs/sam2.1/sam2.1_hiera_l.yaml"


